# Generated by Django 4.2.1 on 2023-05-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('actividad_aerobica', models.BooleanField()),
            ],
        ),
    ]
